# version: '3.8'

services:
  # Backend - Laravel API (Apache)
  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: eclinic-backend
    container_name: eclinic-backend-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - eclinic-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=eclinic
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - RUN_TESTS_ON_BOOT=true

  # Frontend - Next.js
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: eclinic-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - eclinic-network
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NODE_ENV=development
    depends_on:
      - backend-app

  # Database - PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: eclinic-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eclinic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eclinic-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d eclinic"]
      interval: 5s
      timeout: 5s
      retries: 5

  

networks:
  eclinic-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

